# Generated by Django 6.0 on 2025-12-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('dataPublicacao', models.CharField(max_length=50)),
                ('edicao', models.CharField(max_length=50)),
            ],
        ),
    ]
